### ISSUE TITLE
but nils, the `object` crate exists and is good

### ISSUE THREAD

**Issue by alecavi** [Nilstrieb/elven-forest#1]
https://discord.com/channels/273534239310479360/953302976884256768/1074003611190833202

**Comment by SparkyPotato** [comment]
but nils, the `object` crate exists and is good

**Comment by booleancoercion** [comment]
but nils, the `object` crate exists and is good

**Comment by whispersofthedawn** [comment]
but nils, the `object` crate exists and is good

**Comment by Noratrieb** [comment]
i said it's time to write an elf parser
